packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.87.1
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  eslint: ^9.35.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  zod: ^4.1.5

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.0
    react-dom: 19.1.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - utf-8-validate

overrides:
  "@types/minimatch": 5.1.2
