packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.90.5
  "@trpc/client": ^11.6.0
  "@trpc/server": ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  eslint: ^9.37.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.18
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - utf-8-validate

overrides:
  "@expo/metro-runtime": 6.1.2
  "@types/minimatch": 5.1.2
